config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users
  
  namespace :api do
    namespace :v1 do
      resources :poems
    end
  end

  get '/poems/search', to: 'poems#search'
 
  resources :poems do
    member do
      post 'upvote'
      get 'upvote_count'
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'poems#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poem.rb
class Poem < ApplicationRecord
    has_many :votes, dependent: :destroy
    belongs_to :user
    validates_presence_of :content
    paginates_per 2

    def self.search(query)
        attributes = [:title, :content, :author]
        queries = attributes.map { |attr| "#{attr} LIKE '%#{query}%'" }
        where(queries.join(" OR "))
    end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :poems
  has_many :votes
  has_many :voted_poems, -> { distinct }, through: :votes, source: :poem

  def has_voted_for?(poem_id)
    voted_poems.find_by(id: poem_id).present?
  end

  def find_vote_for(poem_id)
    votes.find_by(poem_id: poem_id)
  end

  def vote_for(poem_id)
    return Vote.create(user_id: self.id, poem_id: poem_id)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :poem
    belongs_to :user
end

app/controllers/api/v1/poems_controller.rb
module Api
  module V1
    class PoemsController < ApplicationController
      skip_before_action :verify_authenticity_token
      before_action :doorkeeper_authorize!
      before_action :check_ownership, only: [:show, :update, :destroy]
      respond_to :json
      
      def index
        respond_with current_resource_owner.poems
      end
     
      def show
        respond_with current_resource_owner.poems.find(param_id)
      end
      
      def create
        respond_with current_resource_owner.poems.create(poem_params)
      end
      
      def update
        respond_with Poem.find(param_id).update(poem_params)
      end
      
      def destroy
        respond_with Poem.destroy(param_id)
      end
      
      private 
      
      def poem_params
        params.require(:poem).permit(:title, :content, :author)
      end

      def param_id
        params[:id] || poem_params[:id]
      end

      def check_ownership
        if param_id and Poem.find(param_id).user != current_resource_owner
          render json: {}, status: 401
        end
      end

      def current_resource_owner
        User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]
  before_action :check_ownership, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :upvote_count, :search]
  
  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.order("created_at DESC").page(1)
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = current_user.poems.build()
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    @poem = current_user.poems.build(poem_params)

    if @poem.save
      render json: @poem
    else
      render json: @poem.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem }
      else
        format.html { render :edit }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'Poem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @poem = Poem.find_by(id: params[:id])

    vote = current_user.has_voted_for?(@poem.id) ? current_user.find_vote_for(@poem.id) : current_user.vote_for(@poem.id) 
    if vote
      render json: @poem
    else
      render json: @poem.errors, status: :unprocessable_entity
    end
  end
  
  def upvote_count
    @poem = Poem.find_by(id: params[:id])
    vote_count = @poem&.votes&.count
    if vote_count
      render json: {count: vote_count, by_current_user: current_user&.has_voted_for?(@poem.id)|| false}
    else
      render json: {error: "poem not found"}
    end
  end

  def search
    page = params[:page] || 1
    query = params[:query] || ''

    poems = Poem.search(query).order("created_at DESC").page(params[:page])
    render json: poems
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    def check_ownership
      if @poem.user != current_user
        render json: {}, status: 401
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:author, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoemBot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'poems-bundle' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/poems/_form.html.erb
<%= form_for(poem) do |f| %>
  <% if poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% poem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/_navigation.html.haml
- if user_signed_in?
    =link_to('Sign out', destroy_user_session_path, method: :delete)
    =link_to('New Poem', new_poem_url)
    =link_to('Home', root_path)
- else
    =link_to('Sign In', new_user_session_path)

app/views/poems/edit.html.erb
<h1>Editing Poem</h1>

<%= render 'form', poem: @poem %>

<%= link_to 'Show', @poem %> |
<%= link_to 'Back', poems_path %>

app/views/poems/index.html.haml
= render 'navigation'
= react_component('Poems', props: {poems: @poems, loggedIn: user_signed_in? }, prerender: false)

app/views/poems/new.html.haml
= render 'navigation'
= react_component('PoemForm', props: {poem: @poem}, prerender: false)

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @poem.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @poem.content %>
</p>

<%= link_to 'Edit', edit_poem_path(@poem) %> |
<%= link_to 'Back', poems_path %>